import styles from '@/styles/Home.module.css';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { prove } from "tlsn-js";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  async function getData() {

    // const prove = (await import('tlsn-js')).prove;

    const proof = await prove("https://swapi.dev/api/people/1", {
      method: "GET",
      headers: {
        Connection: "close",
        Accept: "application/json",
        "Accept-Encoding": "identity",
      },
      body: "",
      maxTranscriptSize: 20000,
      notaryUrl: "https://0a05-49-207-214-91.ngrok-free.app",
      websocketProxyUrl: "ws://notary.efprivacyscaling.org:55688",
    });

    console.log(proof);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <button onClick={getData}>Get</button>
      </main>
    </>
  )
}
